
function main(a){
	try{
		try{
		
		}
		catch(JokeException e){
		
		}
	}
	catch(Exception e){
		
	}
}
